# Generated by Django 3.1.7 on 2021-02-23 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210221_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discounted_price',
            new_name='descounted_price',
        ),
    ]
