# Generated by Django 4.1.2 on 2022-10-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_cart_id_alter_customer_id_alter_orderplaced_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='productimg/'),
        ),
    ]
